definitions:
  cmd.Books:
    properties:
      author:
        type: string
      id:
        type: integer
      isbn:
        type: string
      publication_year:
        type: integer
      title:
        type: string
    type: object
  cmd.Request:
    properties:
      books:
        items:
          properties:
            author:
              type: string
            isbn:
              type: string
            publication_year:
              type: integer
            title:
              type: string
          required:
          - author
          - isbn
          - publication_year
          - title
          type: object
        type: array
    required:
    - books
    type: object
host: localhost:8080
info:
  contact: {}
  description: A book catalogue service using gin-framework
  title: Book Catalogue APIs
  version: "1.0"
paths:
  /addBook:
    post:
      consumes:
      - application/json
      description: Add books to the database
      parameters:
      - description: Request object containing books
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/cmd.Request'
      produces:
      - application/json
      responses:
        "200":
          description: Books added successfully
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Add books
  /getBooks:
    get:
      description: Get all books from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cmd.Books'
            type: array
      summary: Get all books
  /getBooksByAuthor:
    get:
      description: Get books by author from the database
      parameters:
      - description: Author name
        in: query
        name: author
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cmd.Books'
            type: array
      summary: Get books by author
  /getBooksById:
    get:
      description: Get a book by ID from the database
      parameters:
      - description: Book ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cmd.Books'
            type: array
      summary: Get book by ID
swagger: "2.0"
